package com.berkeh.connector;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.provider.Settings;import android.text.InputType;import android.view.*;import android.widget.*;
public final class MainActivity extends Activity {
 LinearLayout root,content;TextView status;EditText site,secret,senders;String tab="home";final Handler handler=new Handler(Looper.getMainLooper());boolean visible;final Runnable ticker=new Runnable(){public void run(){if(visible){updateStatus();handler.postDelayed(this,3000);}}};
 int dp(int n){return (int)(getResources().getDisplayMetrics().density*n);}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);if(Build.VERSION.SDK_INT>=35)getWindow().setDecorFitsSystemWindows(false);root=new LinearLayout(this);root.setOrientation(1);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.setBackgroundColor(Color.rgb(243,246,245));root.setPadding(dp(20),dp(18),dp(20),dp(10));root.setOnApplyWindowInsetsListener((v,in)->{int top=in.getSystemWindowInsetTop(),bottom=in.getSystemWindowInsetBottom();v.setPadding(dp(20),top+dp(12),dp(20),bottom+dp(10));return in;});setContentView(root);requestSmsPermissions();TextView title=text("برکه کانکتور",26,true);root.addView(title);root.addView(text("اتصال پیامک بانک به فروشگاه شما",13,false));LinearLayout nav=new LinearLayout(this);for(String t:new String[]{"خانه","اتصال","گزارش"}){Button b1=new Button(this);b1.setText(t);b1.setAllCaps(false);nav.addView(b1,new LinearLayout.LayoutParams(0,dp(54),1));b1.setOnClickListener(v->show(t.equals("خانه")?"home":t.equals("اتصال")?"settings":"logs"));}root.addView(nav);ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(1);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));show(Config.get(this,"site").isEmpty()?"settings":"home");SyncJob.schedule(this);}

 void requestSmsPermissions(){
  if(Build.VERSION.SDK_INT>=23){
   boolean read=checkSelfPermission(Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED;
   boolean receive=checkSelfPermission(Manifest.permission.RECEIVE_SMS)==PackageManager.PERMISSION_GRANTED;
   if(!read || !receive){
    requestPermissions(new String[]{
     Manifest.permission.READ_SMS,
     Manifest.permission.RECEIVE_SMS
    },2001);
   }
  }
 }

 @Override public void onRequestPermissionsResult(int requestCode,String[] permissions,int[] grantResults){
  super.onRequestPermissionsResult(requestCode,permissions,grantResults);
  if(requestCode==2001){
   updateStatus();
  }
 }

 public void onResume(){super.onResume();visible=true;handler.removeCallbacks(ticker);handler.post(ticker);}public void onPause(){visible=false;handler.removeCallbacks(ticker);super.onPause();}
 TextView text(String s,int size,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.rgb(27,46,42));t.setPadding(0,dp(8),0,dp(8));t.setLineSpacing(dp(4),1);if(bold)t.setTypeface(null,Typeface.BOLD);return t;}
 void label(String s){content.addView(text(s,15,true));}void note(String s){content.addView(text(s,14,false));}
 void button(String s,Runnable r){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(22,119,104));d.setCornerRadius(dp(14));b.setBackground(d);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(7),0,dp(7));content.addView(b,p);b.setOnClickListener(v->r.run());}
 EditText field(String caption,String value,boolean password,boolean multi){label(caption);EditText e=new EditText(this);e.setTextSize(15);e.setText(value);e.setTextDirection(View.TEXT_DIRECTION_LTR);e.setInputType(password?129:multi?(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE):InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);e.setMinLines(multi?3:1);if(!multi)e.setSingleLine();content.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
 void show(String which){tab=which;status=null;content.removeAllViews();if(which.equals("settings")){label("اتصال به فروشگاه");note("در وردپرس: کارت‌به‌کارت ← تنظیمات ← API موبایل. کلید مشترک را در این بخش وارد کنید.");site=field("آدرس HTTPS سایت",Config.get(this,"site"),false,false);site.setHint("https://example.com");secret=field("کلید API", "",true,false);secret.setHint(Config.get(this,"secret").isEmpty()?"کلید مشترک افزونه":"خالی بگذارید تا کلید قبلی حفظ شود");senders=field("فرستنده‌های مجاز بانک؛ هر مورد در یک خط",Config.get(this,"senders"),false,true);note("شماره یا نام فرستنده را دقیقاً از پیامک واقعی بانک کپی کنید. تطبیق کامل است؛ لیست خالی هیچ پیامکی را ارسال نمی‌کند. برای ایران‌زمین هم فرستنده واقعی پیامک حساب خود را وارد کنید.");button("ذخیره تنظیمات",()->save());button("آزمایش اتصال ذخیره‌شده",()->test());note("هر نصب به یک سایت وصل می‌شود. برای تغییر سایت ابتدا ارسال را متوقف و صف را پاک کنید. کلید و متن پیامک‌های منتظر ارسال، روی گوشی رمزگذاری می‌شوند.");}
 else if(which.equals("logs")){label("۳۰ پیامک اخیر");try(Store s=new Store(this)){note(s.report());}button("تازه‌سازی گزارش",()->show("logs"));button("تلاش مجدد برای موارد ناموفق",()->{try(Store s=new Store(this)){s.retry();}SyncJob.schedule(this);toast("اگر ارسال فعال باشد، صف دوباره بررسی می‌شود.");});button("پاک کردن صف و گزارش‌ها",()->new AlertDialog.Builder(this).setTitle("حذف اطلاعات محلی؟").setMessage("پیامک‌های ارسال‌نشده هم حذف می‌شوند. اطلاعات ثبت‌شده در سایت حذف نمی‌شوند. ابتدا ارسال را متوقف کنید.").setPositiveButton("حذف",(d,w)->{if(Config.enabled(this)){toast("ابتدا ارسال را از خانه متوقف کنید.");return;}if(SyncJob.running){toast("ارسال جاری در حال پایان است؛ چند ثانیه بعد تلاش کنید.");return;}try(Store s=new Store(this)){s.clear();}show("logs");}).setNegativeButton("انصراف",null).show());}
 else{status=text("",16,true);content.addView(status);updateStatus();button(Config.enabled(this)?"توقف ارسال خودکار":"فعال‌سازی ارسال خودکار",()->toggle());button("ارسال صف اکنون",()->{if(!Config.enabled(this)){toast("ابتدا ارسال را فعال کنید.");return;}SyncJob.schedule(this);new Thread(()->{SyncJob.drain(this);runOnUiThread(()->{updateStatus();toast("صف بررسی شد.");});}).start();});button("آزمایش اتصال",()->test());button("پنل سفارش‌ها و رسیدها",()->{if(Config.get(this,"site").isEmpty()){show("settings");return;}startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(Config.get(this,"site")+"/c2c-app/")));});button("تنظیمات باتری و مجوزهای گوشی",()->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName()))));label("نحوه کار");note("فقط پیامک‌های جدیدِ فرستنده‌های مجاز، پس از فعال‌سازی به سایت خودتان ارسال می‌شوند. پیامک‌های دارای عبارت رمز یا OTP ارسال نمی‌شوند. مبلغ و سفارش در افزونه وردپرس بررسی می‌شود؛ «ارسال شد» به معنی تأیید سفارش نیست.");note("در تنظیمات گوشی، فعالیت پس‌زمینه و باتری نامحدود را برای برکه مجاز کنید. در بعضی گوشی‌ها Auto-start هم لازم است. اندروید ممکن است ارسال پس‌زمینه را به تأخیر بیندازد. پس از Force stop باید اپ را دوباره باز کنید.");note("نسخه ۱.۰.۰ • سازگار با API افزونه ۲.۰.۰\nهیچ پیامک قدیمی از صندوق گوشی خوانده نمی‌شود.");}}
 void updateStatus(){if(status==null)return;try(Store s=new Store(this)){status.setText((Config.enabled(this)?"● ارسال فعال":"○ ارسال متوقف")+"\nمجوز پیامک: "+(checkSelfPermission(Manifest.permission.RECEIVE_SMS)==PackageManager.PERMISSION_GRANTED?"داده شده":"داده نشده")+"\nدر صف: "+s.count("pending")+"    ارسال‌شده: "+s.count("sent")+"    ناموفق: "+s.count("failed")+"\n"+Config.get(this,"last"));}}
 boolean save(){if(Config.enabled(this)){toast("برای تغییر تنظیمات ابتدا ارسال را متوقف کنید.");return false;}try{if(SyncJob.running)throw new Exception("ارسال جاری در حال پایان است؛ چند ثانیه بعد تلاش کنید.");{String url=Config.normalize(site.getText().toString());String sec=secret.getText().toString().trim();try(Store s=new Store(this)){if(!Config.get(this,"site").isEmpty()&&!url.equals(Config.get(this,"site"))&&(s.count("pending")+s.count("failed")>0))throw new Exception("پیش از تغییر سایت، صف قبلی را ارسال یا پاک کنید.");}if(sec.isEmpty()&&Config.get(this,"secret").isEmpty())throw new Exception("کلید API را وارد کنید.");if(!url.equals(Config.get(this,"site"))&&sec.isEmpty())throw new Exception("کلید API سایت جدید را وارد کنید.");SharedPreferences.Editor e=Config.prefs(this).edit().putString("site",url).putString("senders",senders.getText().toString().trim());if(!sec.isEmpty())e.putString("secret",Crypto.encrypt(sec));if(!e.commit())throw new Exception("ذخیره تنظیمات انجام نشد.");secret.setText("");}toast("تنظیمات ذخیره شد.");return true;}catch(Exception e){toast(e.getMessage());return false;}}
 void test(){if(Config.get(this,"site").isEmpty()){toast("ابتدا تنظیمات را ذخیره کنید.");return;}toast("در حال آزمایش اتصال…");new Thread(()->{String result;try{Api.post(this,"auth-check",Api.identity(this));result="اتصال و کلید API معتبر است.";}catch(Exception e){result=Api.explain(e);}final String msg=result;runOnUiThread(()->{Config.prefs(this).edit().putString("last",msg).apply();updateStatus();new AlertDialog.Builder(this).setTitle("نتیجه اتصال").setMessage(msg).setPositiveButton("باشه",null).show();});}).start();}
 void toggle(){if(Config.enabled(this)){Config.prefs(this).edit().putBoolean("enabled",false).commit();SyncJob.cancel(this);show("home");return;}if(Config.get(this,"site").isEmpty()||Config.get(this,"secret").isEmpty()||Config.get(this,"senders").trim().isEmpty()){toast("آدرس، کلید و فرستنده‌های مجاز را تکمیل کنید.");show("settings");return;}new AlertDialog.Builder(this).setTitle("اجازه ارسال پیامک‌های بانکی").setMessage("با فعال‌سازی، متن کامل پیامک‌های جدیدِ فرستنده‌های انتخابی، شامل اطلاعات تراکنش، برای بررسی پرداخت به این سایت ارسال می‌شود:\n"+Config.get(this,"site")+"\n\nاگر اینترنت قطع باشد، پیامک رمزگذاری و برای ارسال مجدد نگهداری می‌شود. ارسال را هر زمان می‌توانید متوقف کنید.").setPositiveButton("موافقم و فعال می‌کنم",(d,w)->{if(checkSelfPermission(Manifest.permission.RECEIVE_SMS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECEIVE_SMS},71);else enable();}).setNegativeButton("انصراف",null).show();}
 void enable(){Config.prefs(this).edit().putBoolean("enabled",true).commit();SyncJob.schedule(this);show("home");}
 public void onRequestPermissionsResult(int req,String[] p,int[] g){super.onRequestPermissionsResult(req,p,g);if(req==71&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)enable();else toast("بدون مجوز پیامک، ارسال خودکار فعال نمی‌شود.");}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
